### ISSUE TITLE
[bug] Using TypeScript decorators throws an error

### ISSUE THREAD

**Issue by bennypowers** [egoist/rollup-plugin-esbuild#139]
Thank you for publishing this very useful package.

Given this file at `packages/docs/copy-code.ts`
<details>
<summary>show copy-code.ts</summary>

```ts
import { customElement, html, internalProperty, LitElement } from 'lit-element'

import ButtonStyles from './button.css';
import CopyStyles from './copy.css';

const supportsClipboard = 'clipboard' in navigator;

@customElement('copy-code')
export class CopyCode extends LitElement {
  static readonly is = 'copy-code';

  static readonly styles = [ButtonStyles, CopyStyles];

  @internalProperty() copyButtonText = 'Copy';

  render() {
    return html`
      <slot></slot>

      <button id="copy-button"
          @click="${this.onCopy}"
          ?hidden="${!supportsClipboard}"
          data-bold="Copied ✅">
        ${this.copyButtonText}
      </button>
    `;
  }

  async onCopy() {
    const { textContent } = this;
    await navigator.clipboard.writeText(textContent.trim());
    this.copyButtonText = 'Copied ✅';
    setTimeout(() => {
      this.copyButtonText = 'Copy';
    }, 2000);
  }
}
```

</details>

and this file at `packages/docs/tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "ESNext",
    "useDefineForClassFields": false,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "moduleResolution": "Node"
  }
}
```

and this file at `rollup.config.docs.js`
```js
/* eslint-env node */
import esbuild from 'rollup-plugin-esbuild';
import nodeResolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import litcss from 'rollup-plugin-lit-css';

export default {
  input: './packages/docs/copy-code.ts',
  output: {
    format: 'es',
    file: './docs/components.js',
  },
  plugins: [
    litcss(),
    esbuild({
      target: 'es2017',
      minify: true,
      sourceMap: true,
      loaders: {
        '.ts': 'ts',
        '.css': 'js',
        '.graphql': 'js',
      },
    }),
    nodeResolve(),
    commonjs(),
  ],
};
```

when running `rollup -c rollup.config.docs.js`, I get this error:

```
yarn run v1.18.0
$ rollup -c rollup.config.docs.js

./packages/docs/components.ts → ./docs/components.js...
[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
packages/docs/copy-code.ts (8:0)
 6: const supportsClipboard = 'clipboard' in navigator;
 7: 
 8: @customElement('copy-code')
    ^
 9: export class CopyCode extends LitElement {
10:   static readonly is = 'copy-code';
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:5251:30)
    at Module.error (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:9810:16)
    at tryParse (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:9691:23)
    at Module.setSource (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:10114:19)
    at ModuleLoader.addModuleSource (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:18275:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ModuleLoader.fetchModule (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:18331:9)
    at async Promise.all (index 0)
    at ModuleLoader.fetchStaticDependencies (/Users/bennyp/Documents/apollo-elements/node_modules/rollup/dist/shared/rollup.js:18356:34)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I would expect this to compile just fine

**Comment by robcresswell** [comment]
I think this may be related to compatibility with `esbuild` `0.8.x`. I've also got unexpected typescript errors

**Comment by hyrious** [comment]
I can not reproduce your error, could you please provide a repo or some small project?
BTW, although vscode suggests you `ES2019` and `ESNext`, esbuild only recognize `es2019` and `esnext` (all lower case).

**Comment by bennypowers** [comment]
Updating dependencies has solved this for me. 

Thanks!
