### ISSUE TITLE
SyntaxError: The requested module 'es-module-lexer' does not provide an export named 'default'

### ISSUE THREAD

**Issue by mvdschee** [egoist/rollup-plugin-esbuild#325]
`src/optimizer/optmize-deps.ts` uses `es-module-lexer'` which says gives the following error in unbuild

```bash
yarn run v1.22.15
$ unbuild
[hidden]/ual-wax/node_modules/rollup-plugin-esbuild/dist/index.mjs:125
import esModuleLexer from "es-module-lexer";
       ^^^^^^^^^^^^^
SyntaxError: The requested module 'es-module-lexer' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:121:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
error Command failed with exit code 1.
```

**Comment by mvdschee** [comment]
package recommended usage https://github.com/guybedford/es-module-lexer/tree/main#usage

```js
import { init, parse } from 'es-module-lexer';
```

or if you want it named
```js
import * as esModuleLexer from 'es-module-lexer';
```
